package com.bwie.retrofitdesigndemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwie.retrofitdesigndemo.entity.HomeDao;

import com.bwie.retrofitdesigndemo.greendao.HomeDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeDaoDaoConfig;

    private final HomeDaoDao homeDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeDaoDaoConfig = daoConfigMap.get(HomeDaoDao.class).clone();
        homeDaoDaoConfig.initIdentityScope(type);

        homeDaoDao = new HomeDaoDao(homeDaoDaoConfig, this);

        registerDao(HomeDao.class, homeDaoDao);
    }
    
    public void clear() {
        homeDaoDaoConfig.clearIdentityScope();
    }

    public HomeDaoDao getHomeDaoDao() {
        return homeDaoDao;
    }

}
